/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    DataHistoryWidget: typeof import('./src/components/dashboard/DataHistoryWidget.vue')['default']
    DeliveryProcessWidget: typeof import('./src/components/dashboard/DeliveryProcessWidget.vue')['default']
    DocumentHandlingWidget: typeof import('./src/components/dashboard/DocumentHandlingWidget.vue')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    MetodeFollowUpWidget: typeof import('./src/components/dashboard/MetodeFollowUpWidget.vue')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    PaymentTypeWidget: typeof import('./src/components/dashboard/PaymentTypeWidget.vue')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SebaranDataMapWidget: typeof import('./src/components/dashboard/SebaranDataMapWidget.vue')['default']
    SebaranDataSimpleWidget: typeof import('./src/components/dashboard/SebaranDataSimpleWidget.vue')['default']
    SebaranDataWidget: typeof import('./src/components/dashboard/SebaranDataWidget.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    StatusProspectBarWidget: typeof import('./src/components/dashboard/StatusProspectBarWidget.vue')['default']
    StatusProspectWidget: typeof import('./src/components/dashboard/StatusProspectWidget.vue')['default']
    StatusSPKWidget: typeof import('./src/components/dashboard/StatusSPKWidget.vue')['default']
    SumberProspectWidget: typeof import('./src/components/dashboard/SumberProspectWidget.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
    TopLeasingWidget: typeof import('./src/components/dashboard/TopLeasingWidget.vue')['default']
    UnitInboundStatusWidget: typeof import('./src/components/dashboard/UnitInboundStatusWidget.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
